// 悬浮小助手 - 快捷指令配置

import type { ModuleKey, QuickCommand } from './types'

export const quickCommands: QuickCommand[] = [
  // ── 沉降模块 ──
  {
    id: 'settlement-report',
    title: '生成本周沉降报告',
    icon: '📊',
    prompt: '请生成本周的沉降监测报告，包括：1. 整体趋势分析 2. 异常点位统计 3. 风险预警 4. 处置建议',
    role: 'reporter',
    modules: ['settlement'],
    mode: 'both',
    category: '报告生成',
    description: '自动生成包含趋势分析、异常统计和风险预警的周报',
    tags: ['报告', '周报', '趋势', '异常'],
  },
  {
    id: 'settlement-agent-analysis',
    title: '智能沉降数据分析',
    icon: '🤖',
    prompt: '请使用工具查询最近7天的沉降数据，自动识别异常点位，计算变化率，生成可视化图表，并给出专业分析报告',
    role: 'researcher',
    modules: ['settlement'],
    mode: 'agent',
    category: '智能分析',
    description: 'Agent 模式：自动查询数据、计算指标、生成图表',
    tags: ['agent', '自动化', '数据查询', '可视化'],
  },
  {
    id: 'settlement-chat-explain',
    title: '解释沉降原理',
    icon: '💡',
    prompt: '请用通俗易懂的语言解释地表沉降的形成原理、监测方法和控制标准',
    role: 'worker',
    modules: ['settlement'],
    mode: 'chat',
    category: '知识问答',
    description: 'Chat 模式：基于知识库回答问题，不查询实时数据',
    tags: ['原理', '知识', '教学'],
  },
  {
    id: 'settlement-anomalies',
    title: '检查沉降异常点位',
    icon: '⚠️',
    prompt: '请检查当前所有沉降监测点的异常情况，按严重程度排序，并给出处置建议',
    role: 'worker',
    modules: ['settlement'],
    mode: 'both',
    category: '异常检测',
    description: '快速识别异常点位并提供处置建议',
    tags: ['异常', '检查', '排序'],
  },
  {
    id: 'settlement-agent-compare',
    title: '多点位对比分析',
    icon: '📈',
    prompt: '请查询选定的多个沉降点位数据，生成对比图表，分析各点位的变化特征和相互关系',
    role: 'researcher',
    modules: ['settlement'],
    mode: 'agent',
    category: '对比分析',
    description: 'Agent 模式：自动查询多点数据并生成对比图表',
    tags: ['对比', '多点位', '图表'],
  },
  {
    id: 'settlement-chat-standard',
    title: '沉降控制标准查询',
    icon: '📋',
    prompt: '请告诉我地铁隧道沉降监测的控制标准、预警阈值和分级管理要求',
    role: 'worker',
    modules: ['settlement'],
    mode: 'chat',
    category: '标准规范',
    description: 'Chat 模式：查询行业标准和规范要求',
    tags: ['标准', '规范', '阈值'],
  },
  {
    id: 'settlement-predict',
    title: '预测沉降趋势',
    icon: '🔮',
    prompt: '请预测未来 30 天的沉降趋势，识别高风险点位，并分析可能的原因',
    role: 'researcher',
    modules: ['settlement'],
    mode: 'both',
    category: '趋势预测',
    description: '基于历史数据预测未来趋势',
    tags: ['预测', '趋势', '风险'],
  },
  {
    id: 'settlement-agent-export',
    title: '自动生成导出报告',
    icon: '📥',
    prompt: '请查询本月所有沉降数据，生成包含统计表格、趋势图表和分析结论的完整报告，并提供下载链接',
    role: 'reporter',
    modules: ['settlement'],
    mode: 'agent',
    category: '数据导出',
    description: 'Agent 模式：自动查询、分析、生成报告文件',
    tags: ['导出', '报告', '自动化'],
  },
  {
    id: 'settlement-chat-case',
    title: '沉降案例学习',
    icon: '📚',
    prompt: '请分享一些地铁施工引起地表沉降的典型案例，包括原因分析和处置措施',
    role: 'researcher',
    modules: ['settlement'],
    mode: 'chat',
    category: '案例学习',
    description: 'Chat 模式：学习行业案例和经验',
    tags: ['案例', '学习', '经验'],
  },
  {
    id: 'settlement-inspection',
    title: '沉降巡检清单',
    icon: '📋',
    prompt: '请生成今日需要巡检的沉降点位清单，按优先级排序，并说明巡检重点',
    role: 'worker',
    modules: ['settlement'],
    mode: 'both',
    category: '巡检管理',
    description: '生成优先级排序的巡检清单',
    tags: ['巡检', '清单', '优先级'],
  },

  // ── 温度模块 ──
  {
    id: 'temperature-report',
    title: '生成温度监测报告',
    icon: '📊',
    prompt: '请生成当前温度监测报告，包括：1. 各测点温度分布 2. 异常高温/低温点位 3. 温度变化趋势 4. 处置建议',
    role: 'reporter',
    modules: ['temperature'],
    mode: 'both',
    category: '报告生成',
    description: '生成包含温度分布和趋势的监测报告',
    tags: ['报告', '温度', '趋势'],
  },
  {
    id: 'temperature-agent-heatmap',
    title: '生成温度热力图',
    icon: '🗺️',
    prompt: '请查询所有温度监测点的最新数据，生成温度分布热力图，标注高温和低温区域',
    role: 'researcher',
    modules: ['temperature'],
    mode: 'agent',
    category: '可视化分析',
    description: 'Agent 模式：自动查询数据并生成热力图',
    tags: ['热力图', '可视化', '分布'],
  },
  {
    id: 'temperature-anomalies',
    title: '检查温度异常',
    icon: '⚠️',
    prompt: '请检查当前所有温度监测点的异常情况，识别超温或温差过大的点位，并给出处置建议',
    role: 'worker',
    modules: ['temperature'],
    mode: 'both',
    category: '异常检测',
    description: '识别超温和温差异常点位',
    tags: ['异常', '超温', '温差'],
  },
  {
    id: 'temperature-chat-impact',
    title: '温度对结构的影响',
    icon: '💡',
    prompt: '请解释温度变化对混凝土结构和地铁隧道的影响机理，以及如何进行温度控制',
    role: 'researcher',
    modules: ['temperature'],
    mode: 'chat',
    category: '知识问答',
    description: 'Chat 模式：解释温度影响机理',
    tags: ['原理', '影响', '控制'],
  },
  {
    id: 'temperature-correlation',
    title: '温度-沉降关联分析',
    icon: '🔮',
    prompt: '请分析温度变化与沉降之间的关联性，找出温度对沉降影响最显著的区域',
    role: 'researcher',
    modules: ['temperature'],
    mode: 'agent',
    category: '关联分析',
    description: 'Agent 模式：分析温度与沉降的关联',
    tags: ['关联', '沉降', '影响'],
  },

  // ── 裂缝模块 ──
  {
    id: 'crack-report',
    title: '生成裂缝监测报告',
    icon: '📊',
    prompt: '请生成当前裂缝监测报告，包括：1. 裂缝分布统计 2. 宽度/深度变化趋势 3. 新增裂缝情况 4. 处置建议',
    role: 'reporter',
    modules: ['cracks'],
    mode: 'both',
    category: '报告生成',
    description: '生成裂缝分布和发展趋势报告',
    tags: ['报告', '裂缝', '统计'],
  },
  {
    id: 'crack-agent-growth',
    title: '裂缝发展速率分析',
    icon: '📈',
    prompt: '请查询所有裂缝点位的历史数据，计算各裂缝的发展速率，识别快速发展的裂缝并预警',
    role: 'researcher',
    modules: ['cracks'],
    mode: 'agent',
    category: '速率分析',
    description: 'Agent 模式：计算发展速率并预警',
    tags: ['速率', '发展', '预警'],
  },
  {
    id: 'crack-anomalies',
    title: '检查裂缝异常',
    icon: '⚠️',
    prompt: '请检查当前所有裂缝监测点的异常情况，识别快速发展的裂缝，并给出处置建议',
    role: 'worker',
    modules: ['cracks'],
    mode: 'both',
    category: '异常检测',
    description: '识别快速发展的裂缝',
    tags: ['异常', '快速发展', '处置'],
  },
  {
    id: 'crack-chat-repair',
    title: '裂缝修复方案咨询',
    icon: '🔧',
    prompt: '请介绍不同类型裂缝的修复方法、材料选择和施工要点',
    role: 'worker',
    modules: ['cracks'],
    mode: 'chat',
    category: '知识问答',
    description: 'Chat 模式：咨询裂缝修复方案',
    tags: ['修复', '方案', '施工'],
  },
  {
    id: 'crack-trend',
    title: '裂缝发展趋势分析',
    icon: '🔮',
    prompt: '请分析各裂缝点位的发展趋势，预测未来可能恶化的裂缝，并提出加固建议',
    role: 'researcher',
    modules: ['cracks'],
    mode: 'both',
    category: '趋势预测',
    description: '预测裂缝发展趋势',
    tags: ['趋势', '预测', '加固'],
  },

  // ── 振动模块 ──
  {
    id: 'vibration-report',
    title: '生成振动监测报告',
    icon: '📊',
    prompt: '请生成当前振动监测报告，包括：1. 振动强度分布 2. 超标点位统计 3. 频谱特征分析 4. 处置建议',
    role: 'reporter',
    modules: ['vibration'],
    mode: 'both',
    category: '报告生成',
    description: '生成振动强度和频谱分析报告',
    tags: ['报告', '振动', '频谱'],
  },
  {
    id: 'vibration-anomalies',
    title: '检查振动超标',
    icon: '⚠️',
    prompt: '请检查当前所有振动监测点的超标情况，识别振动源，并给出减振建议',
    role: 'worker',
    modules: ['vibration'],
    mode: 'both',
    category: '异常检测',
    description: '识别振动超标点位',
    tags: ['异常', '超标', '减振'],
  },
  {
    id: 'vibration-agent-spectrum',
    title: '振动频谱分析',
    icon: '📊',
    prompt: '请查询振动监测数据，进行频谱分析，识别振动频率特征，判断振动源类型',
    role: 'researcher',
    modules: ['vibration'],
    mode: 'agent',
    category: '频谱分析',
    description: 'Agent 模式：频谱分析识别振动源',
    tags: ['频谱', '分析', '振动源'],
  },

  // ── InSAR 模块 ──
  {
    id: 'insar-report',
    title: '生成 InSAR 分析报告',
    icon: '📊',
    prompt: '请生成当前 InSAR 监测报告，包括：1. 地表形变分布 2. 形变速率分析 3. 重点区域识别 4. 与地面监测对比',
    role: 'reporter',
    modules: ['insar'],
    mode: 'both',
    category: '报告生成',
    description: '生成 InSAR 地表形变分析报告',
    tags: ['InSAR', '形变', '报告'],
  },
  {
    id: 'insar-compare',
    title: 'InSAR 与地面数据对比',
    icon: '🔮',
    prompt: '请对比 InSAR 遥感数据与地面沉降监测数据，分析一致性和差异，评估数据可靠性',
    role: 'researcher',
    modules: ['insar'],
    mode: 'agent',
    category: '对比分析',
    description: 'Agent 模式：对比遥感与地面数据',
    tags: ['对比', 'InSAR', '地面监测'],
  },
  {
    id: 'insar-chat-principle',
    title: 'InSAR 技术原理',
    icon: '💡',
    prompt: '请解释 InSAR 技术的工作原理、优势和局限性，以及如何与地面监测数据结合使用',
    role: 'researcher',
    modules: ['insar'],
    mode: 'chat',
    category: '知识问答',
    description: 'Chat 模式：解释 InSAR 技术原理',
    tags: ['原理', 'InSAR', '技术'],
  },

  // ── 高级分析模块 ──
  {
    id: 'advanced-diagnosis',
    title: '智能异常诊断',
    icon: '⚠️',
    prompt: '请对所有监测数据进行综合异常诊断，识别异常点位，按严重程度分级，并给出处置建议',
    role: 'researcher',
    modules: ['advanced'],
    mode: 'agent',
    category: '智能诊断',
    description: 'Agent 模式：综合多源数据智能诊断',
    tags: ['诊断', '异常', '综合'],
  },
  {
    id: 'advanced-predict',
    title: '多点位趋势预测',
    icon: '🔮',
    prompt: '请对所有高风险点位进行趋势预测，预测未来 30 天的变化，并识别可能超限的点位',
    role: 'researcher',
    modules: ['advanced'],
    mode: 'agent',
    category: '趋势预测',
    description: 'Agent 模式：多点位趋势预测',
    tags: ['预测', '趋势', '多点位'],
  },
  {
    id: 'advanced-causal',
    title: '施工事件影响分析',
    icon: '🏗️',
    prompt: '请分析最近的施工事件对沉降的影响，量化影响程度，并评估是否需要采取措施',
    role: 'researcher',
    modules: ['advanced'],
    mode: 'agent',
    category: '因果分析',
    description: 'Agent 模式：分析施工事件影响',
    tags: ['因果', '施工', '影响'],
  },
  {
    id: 'advanced-spatial',
    title: '空间关联分析',
    icon: '🗺️',
    prompt: '请分析监测点之间的空间关联性，识别影响传播路径，并标注高风险区域',
    role: 'researcher',
    modules: ['advanced'],
    mode: 'agent',
    category: '空间分析',
    description: 'Agent 模式：空间关联分析',
    tags: ['空间', '关联', '传播'],
  },

  // ── 数据总览模块 ──
  {
    id: 'overview-summary',
    title: '生成数据总览摘要',
    icon: '📊',
    prompt: '请生成当前所有监测数据的总览摘要，包括各类数据的关键指标、异常统计和整体趋势',
    role: 'reporter',
    modules: ['overview'],
    mode: 'both',
    category: '数据总览',
    description: '生成所有监测数据摘要',
    tags: ['总览', '摘要', '综合'],
  },
  {
    id: 'overview-risk',
    title: '综合风险评估',
    icon: '⚠️',
    prompt: '请综合沉降、温度、裂缝、振动等多源数据，进行综合风险评估，识别高风险区域',
    role: 'researcher',
    modules: ['overview'],
    mode: 'agent',
    category: '风险评估',
    description: 'Agent 模式：综合风险评估',
    tags: ['风险', '评估', '综合'],
  },

  // ── 工单模块 ──
  {
    id: 'tickets-overdue',
    title: '检查逾期工单',
    icon: '⚠️',
    prompt: '请检查当前所有逾期未完成的工单，列出负责人、逾期天数，并给出催办建议',
    role: 'worker',
    modules: ['tickets'],
    mode: 'both',
    category: '工单管理',
    description: '检查逾期工单',
    tags: ['工单', '逾期', '催办'],
  },
  {
    id: 'tickets-stats',
    title: '工单统计分析',
    icon: '📊',
    prompt: '请统计当前工单的完成情况，包括各状态工单数量、平均处理时间、各类型分布',
    role: 'reporter',
    modules: ['tickets'],
    mode: 'both',
    category: '统计分析',
    description: '工单统计分析',
    tags: ['工单', '统计', '分析'],
  },

  // ── 盾构轨迹模块 ──
  {
    id: 'shield-status',
    title: '盾构推进状态',
    icon: '📊',
    prompt: '请分析当前盾构推进状态，包括推进速度、偏差情况、姿态参数，并评估是否需要纠偏',
    role: 'worker',
    modules: ['shield-trajectory'],
    mode: 'both',
    category: '状态监控',
    description: '分析盾构推进状态',
    tags: ['盾构', '推进', '状态'],
  },
  {
    id: 'shield-impact',
    title: '盾构对沉降的影响',
    icon: '🔮',
    prompt: '请分析盾构推进对周边地表沉降的影响范围和程度，预测后续影响趋势',
    role: 'researcher',
    modules: ['shield-trajectory'],
    mode: 'agent',
    category: '影响分析',
    description: 'Agent 模式：分析盾构对沉降的影响',
    tags: ['盾构', '沉降', '影响'],
  },

  // ── 通用指令（所有模块可用）──
  {
    id: 'general-help',
    title: '系统使用帮助',
    icon: '📋',
    prompt: '请介绍当前页面的功能和使用方法，帮助我快速上手',
    role: 'worker',
    mode: 'chat',
    category: '使用帮助',
    description: 'Chat 模式：系统使用指导',
    tags: ['帮助', '指导', '教程'],
  },
  {
    id: 'general-export',
    title: '导出数据建议',
    icon: '📊',
    prompt: '请告诉我当前页面有哪些数据可以导出，以及推荐的导出格式和用途',
    role: 'reporter',
    mode: 'chat',
    category: '数据导出',
    description: 'Chat 模式：导出建议',
    tags: ['导出', '建议', '格式'],
  },
  {
    id: 'general-chat-qa',
    title: '专业知识问答',
    icon: '💬',
    prompt: '我有一些关于地铁监测的专业问题想咨询',
    role: 'researcher',
    mode: 'chat',
    category: '知识问答',
    description: 'Chat 模式：专业知识咨询',
    tags: ['问答', '咨询', '知识'],
  },
  {
    id: 'general-agent-custom',
    title: '自定义数据分析',
    icon: '🤖',
    prompt: '我需要进行一些自定义的数据查询和分析',
    role: 'researcher',
    mode: 'agent',
    category: '自定义分析',
    description: 'Agent 模式：自定义数据分析',
    tags: ['自定义', '分析', 'agent'],
  },
]

/** 从路由路径推导模块 key */
export function pathToModule(pathname: string): ModuleKey {
  const seg = pathname.replace(/^\//, '').split('/')[0]
  const map: Record<string, ModuleKey> = {
    settlement: 'settlement',
    temperature: 'temperature',
    cracks: 'cracks',
    vibration: 'vibration',
    insar: 'insar',
    advanced: 'advanced',
    overview: 'overview',
    three: 'three',
    tickets: 'tickets',
    'shield-trajectory': 'shield-trajectory',
    cover: 'cover',
    tunnel: 'general',
    modules: 'general',
  }
  return map[seg] || 'general'
}

export const roleConfig = {
  researcher: {
    label: '科研人员',
    color: '#8b5cf6',
    icon: '🔬',
    description: '专业详细，引用数据和算法',
  },
  worker: {
    label: '施工人员',
    color: '#f59e0b',
    icon: '👷',
    description: '简单直白，可操作性强',
  },
  reporter: {
    label: '项目汇报',
    color: '#10b981',
    icon: '📈',
    description: '总结性强，适合展示',
  },
}
